export interface LeaderboardEntry {
    id: number;
    teamName: string;
    projectName: string;
    hackCoins: number;
    members: number;
    achievement: string;
    wins: number;
}

export const leaderboardData: LeaderboardEntry[] = [
    {
        id: 1,
        teamName: "Code Wizards",
        projectName: "AI Assistant",
        hackCoins: 2500,
        members: 4,
        achievement: "Most Innovative",
        wins: 10,
    },
    {
        id: 2,
        teamName: "Byte Busters",
        projectName: "EcoTrack",
        hackCoins: 2300,
        members: 3,
        achievement: "Best UI/UX",
        wins: 8,
    },
    {
        id: 3,
        teamName: "Data Dynamos",
        projectName: "HealthHub",
        hackCoins: 2100,
        members: 5,
        achievement: "Best Use of Data",
        wins: 7,
    },
    {
        id: 4,
        teamName: "Tech Titans",
        projectName: "SmartCity",
        hackCoins: 2000,
        members: 4,
        achievement: "Most Scalable",
        wins: 6,
    },
    {
        id: 5,
        teamName: "Quantum Questers",
        projectName: "CryptoSafe",
        hackCoins: 1900,
        members: 3,
        achievement: "Best Blockchain Solution",
        wins: 5,
    },
    {
        id: 6,
        teamName: "AI Avengers",
        projectName: "RoboTutor",
        hackCoins: 1800,
        members: 4,
        achievement: "Best AI Implementation",
        wins: 9,
    },
    {
        id: 7,
        teamName: "Cloud Crusaders",
        projectName: "ServerlessPro",
        hackCoins: 1700,
        members: 3,
        achievement: "Best Cloud Architecture",
        wins: 4,
    },
    {
        id: 8,
        teamName: "Mobile Mavericks",
        projectName: "AR Navigator",
        hackCoins: 1600,
        members: 4,
        achievement: "Best Mobile App",
        wins: 3,
    },
    {
        id: 9,
        teamName: "Security Sentinels",
        projectName: "CyberShield",
        hackCoins: 1500,
        members: 3,
        achievement: "Best Security Solution",
        wins: 2,
    },
    {
        id: 10,
        teamName: "IoT Innovators",
        projectName: "SmartHome",
        hackCoins: 1400,
        members: 5,
        achievement: "Best IoT Project",
        wins: 7,
    },
    {
        id: 11,
        teamName: "Web Wonders",
        projectName: "AccessAll",
        hackCoins: 1300,
        members: 3,
        achievement: "Most Accessible",
        wins: 1,
    },
    {
        id: 12,
        teamName: "Game Gurus",
        projectName: "EduQuest",
        hackCoins: 1200,
        members: 4,
        achievement: "Best Educational Game",
        wins: 5,
    },
    {
        id: 13,
        teamName: "DevOps Dynamos",
        projectName: "PipelinePro",
        hackCoins: 1100,
        members: 3,
        achievement: "Best DevOps Solution",
        wins: 3,
    },
    {
        id: 14,
        teamName: "Fintech Phoenixes",
        projectName: "CryptoWallet",
        hackCoins: 1000,
        members: 4,
        achievement: "Best Fintech Solution",
        wins: 2,
    },
    {
        id: 15,
        teamName: "VR Visionaries",
        projectName: "VirtualClass",
        hackCoins: 900,
        members: 5,
        achievement: "Best VR Experience",
        wins: 6,
    },
    {
        id: 16,
        teamName: "Green Coders",
        projectName: "EcoEnergy",
        hackCoins: 800,
        members: 3,
        achievement: "Most Sustainable",
        wins: 4,
    },
    {
        id: 17,
        teamName: "Data Detectives",
        projectName: "FraudBuster",
        hackCoins: 700,
        members: 4,
        achievement: "Best Data Analysis",
        wins: 1,
    },
    {
        id: 18,
        teamName: "UX Unicorns",
        projectName: "AccessUI",
        hackCoins: 600,
        members: 3,
        achievement: "Most User-Friendly",
        wins: 8,
    },
    {
        id: 19,
        teamName: "API Alchemists",
        projectName: "IntegrationHub",
        hackCoins: 500,
        members: 4,
        achievement: "Best API Integration",
        wins: 3,
    },
    {
        id: 20,
        teamName: "ML Mavericks",
        projectName: "PredictPro",
        hackCoins: 400,
        members: 5,
        achievement: "Best Machine Learning Model",
        wins: 2,
    },
];
